version: 0.2

phases:
  install:
    commands:
      - echo Updating everything...
      - apt-get update -y && apt-get upgrade -y
      - echo Installing package.json dependencies...
      - npm install
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@^12.2.15
      - echo Installing headless Chrome for testing.
      - apt-get install curl wget libxss1 libappindicator1 libindicator7 -y
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt install ./google-chrome*.deb -y
  pre_build:
    commands:
      - ng t ng-dk-public-service --watch=false --browsers=ChromeHeadlessCI
  build:
    commands:
      - ng b ng-dk-public-service -c production
  post_build:
    commands:
      - CURRENT_VERSION=$(npm show -q @diamondkinetics/ng-dk-public-service version)
      - SRC_VERSION=$(node -pe "require('./package.json').version")
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - if [ "$CURRENT_VERSION" != "$SRC_VERSION" ]; then cd dist/ng-dk-public-service && npm publish --access=public; fi
      - if [ "$CURRENT_VERSION" = "$SRC_VERSION "]; then echo "No new version to publish (Currently $CURRENT_VERSION)."; fi
artifacts:
  files:
    - dist/ng-dk-public-service/**/*
