version: 0.2

phases:
  install:
    commands:
      - echo Installing package.json dependencies...
      - npm install
      - echo installing Angular CLI...
      - npm install -g @angular/cli@12.1.3
  pre_build:
    commands:
      - ng t ng-dk-public-service
  build:
    commands:
      - npm run-script build
  post_build:
    commands:
      - CURRENT_VERSION=$(npm show -q @diamondkinetics/dk-ng-dk-public-service version)
      - SRC_VERSION=$(node -pe "require('./package.json').version")
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - if [ "$CURRENT_VERSION" != "$SRC_VERSION" ]; then npm publish --access=public; fi
      - if [ "$CURRENT_VERSION" = "$SRC_VERSION "]; then echo "No new version to publish (Currently $CURRENT_VERSION)."; fi
artifacts:
  files:
    - build/**/*
